### ISSUE TITLE
Backend API endpoint unexpectedly references "ccvg"

### ISSUE THREAD

**Issue by ctgraham** [ulsdevteam/ccvgd-frontend#11]
Configuring a production build with the environment:
```
export const environment = {
  production: true,
  //backend service will run on this API ROOT, which points to the server
  API_ROOT: "//test.hostname.tld:8001/api/",
};
```

Constructs backend API calls such as:
`http://test.hostname.tld:8001/api/ccvg/namesearch`

But there is no guarantee that "ccvg" is a prefix in the deployment of the backend.

**Comment by ctgraham** [comment]
For example:
https://github.com/ulsdevteam/ccvgd-frontend/blob/2bfe6adcd44b5a8d2c86decb8d21e46ea47d3671/src/app/services/multi-village-filter.service.ts#L32-L33
and
https://github.com/ulsdevteam/ccvgd-frontend/blob/2bfe6adcd44b5a8d2c86decb8d21e46ea47d3671/src/app/services/multi-village-filter.service.ts#L51-L52

Also, beware of code which hardcodes the endpoint, such as:
https://github.com/ulsdevteam/ccvgd-frontend/blob/f58ccb17685a71be9d8981a19cc33a3e3db27589/src/app/table-detail/table-detail.component.ts#L62-L68

**Comment by Xiaoxin-He** [comment]
since all the API call for the backend has ccvg as prefix included, we don't need to consider if ccvg has no guarantee.

**Comment by Xiaoxin-He** [comment]
Here is the reply from yuelu (backend developer) : This 'ccvg' is actucally the hard code prefix of our backend deployment of Dr. He's server. Once we are not in that server Xiaoxin Can change this in our Library version.

**Comment by ctgraham** [comment]
The hardcoded component "ccvg" should appear in the `API_ROOT` definition, not in the code.

That way it will work both with on Dr. He's server, and in an arbitrary install where the path is different.

**Comment by Xiaoxin-He** [comment]
Thanks Clinton, it is make sense

**Comment by Xiaoxin-He** [comment]
Due to the CORS policy issue happen on the server again, I unable to test it and push the new api call, 
Do you have any ideas to fix this?

<img width="696" alt="Screen Shot 2021-08-04 at 5 32 44 PM" src="https://user-images.githubusercontent.com/43584974/128257844-e3c9325e-693c-44a3-87df-a1751780c2e3.png">

**Comment by Xiaoxin-He** [comment]
it struggles me a lot , the server is not stable,
every time I need to contact Yuelu(backend developer) to restart the server

**Comment by Xiaoxin-He** [comment]
ccvg as prefix is added to enviroment.prod.ts

**Comment by ctgraham** [comment]
There remain a number of locations where the prefix or whole URL appears to still be hardcoded:

- https://github.com/ulsdevteam/ccvgd-frontend/blob/2bfe6adcd44b5a8d2c86decb8d21e46ea47d3671/src/app/services/multi-village-filter.service.ts#L33
- https://github.com/ulsdevteam/ccvgd-frontend/blob/f58ccb17685a71be9d8981a19cc33a3e3db27589/src/app/services/village-name.service.ts#L23
- https://github.com/ulsdevteam/ccvgd-frontend/blob/f58ccb17685a71be9d8981a19cc33a3e3db27589/src/app/table-detail/table-detail.component.ts#L63
- https://github.com/ulsdevteam/ccvgd-frontend/blob/f58ccb17685a71be9d8981a19cc33a3e3db27589/src/app/services/single-village-search-result.service.ts#L52
- https://github.com/ulsdevteam/ccvgd-frontend/blob/5e7da0824a8f675b784dc557dc793a52a011cc0e/src/app/search-multi-villages/search-multi-villages.component.ts#L315
- https://github.com/ulsdevteam/ccvgd-frontend/blob/f58ccb17685a71be9d8981a19cc33a3e3db27589/src/app/single-village-search-result/single-village-search-result.component.ts#L719

**Comment by Xiaoxin-He** [comment]
all are updated, please see the latest commit , thanks!
