### ISSUE TITLE
Backend endpoint should consider HTTP and HTTPS

### ISSUE THREAD

**Issue by ctgraham** [ulsdevteam/ccvgd-frontend#12]
In `src/environments/environment*.ts`, we have a single key for `API_ROOT`, with an example of an "http" endpoint.  E.g.:
https://github.com/ulsdevteam/ccvgd-frontend/blob/5e62deb900d732f1a00efc08551edeea6805087b/src/environments/environment.ts#L7

This application itself should be able to be served over HTTP or HTTPS, at the end user's preference.

Because this API endpoint is called from the end user's web browser, via the application itself, this configuration would suggest that either the entire application should be placed behind a proxy, or that the backend API should be available to the end user via both HTTP and HTTPS.

If the example deployment will reference an HTTP endpoint, the example should also so how to configure an HTTPS endpoint as well.

If the example deployment references a relative path (that is, `API_ROOT: "/backend-api/"` or `API_ROOT: "//localhost/backend/"`), then the determination of HTTP or HTTPS can be left to the administrator who is installing the application.

**Comment by Xiaoxin-He** [comment]
Here is the reply from yuelu (backend developer) : Professor He's server does not support HTTPS, once and if we need this HTTPS maybe we can use the backend URL of the library to change the current HTTP one.

**Comment by ctgraham** [comment]
This will primarily be a consideration for the front end application.  If the application is available via a single protocol only, then a single `API_ROOT` endpoint is appropriate, because we can reference the protocol there (as we do now).  If the application is available only with the backend on the same domain as the frontend, then a single `API_ROOT` endpoint is appropriate, because we can use a relative path for the `API_ROOT`.

If we want to enforce that the application can only be deployed via a single protocol, or can only be deployed with a relative path reference to the backend, this needs to be documented in the README.

The simplest solution is probably to confirm that the application still works with a protocol-less URL in the config, e.g.: "//ngrok.luozm.me:8395/ccvg/"

**Comment by Xiaoxin-He** [comment]
Since the backend server only consider HTTP, could we use only http for the frontend instead?

**Comment by ctgraham** [comment]
As long as the frontend application will work with a relative path as the `API_ROOT`, there's no concern about deploying.  In the ULS server, we'll be able to serve both HTTP and HTTPS, for the frontend and backend.

The minimum we need to do here is document that this `API_ROOT` endpoint selected must be exposed to the end user (as opposed to an endpoint which is called server-side).

**Comment by ctgraham** [comment]
Resolved via https://github.com/ulsdevteam/ccvgd-integral/issues/1
