### ISSUE TITLE
Public facing URIs are not linkable/resolvable

### ISSUE THREAD

**Issue by ctgraham** [ulsdevteam/ccvgd-frontend#23]
When deployed as an application in an Apache document root, the application responds and re-writes the public-facing URLs to endpoints such as `/single-village-search` and `/multi-village-search`.

![image](https://user-images.githubusercontent.com/7001322/130692879-d53ad4f1-2d0b-4a9f-88ce-20eb6eec46a2.png)

![image](https://user-images.githubusercontent.com/7001322/130692941-9c7030db-9213-4a28-ba77-085be724b67e.png)

but direct fetches of these endpoints result in 404s.

![image](https://user-images.githubusercontent.com/7001322/130693003-6caf1928-8c37-4fdb-8b96-a79dfbfd3a6e.png)

![image](https://user-images.githubusercontent.com/7001322/130692976-62643783-4a03-4c5f-97e3-05e97943692d.png)

What is the expected server-level redirection needed to ensure that public facing URLs are directed to the js application?

**Comment by Xiaoxin-He** [comment]
Thank you, Clinton! For this summer break, I am working on the multi-village search, and right now I am fixing some of those features and make sure to reach all the requirements from the clients, those API calls should be fixed soon but only after they think all the multi-village search features are done.

**Comment by ctgraham** [comment]
For clarity, the 404s are not coming API calls to the backend, but rather requests to the frontend pages.  For example, clicking on 多村庄搜索 from the homepage, and then hitting the browser's refresh/reload button returns a 404.

I thought that links might require the anchor hash, like `http://hostname.tld/#multi-village-search`, but this just redirected to `http://hostname.tld/single-village-search`.

**Comment by Xiaoxin-He** [comment]
Got you! That's made more sense now!

**Comment by ctgraham** [comment]
Not currently reproducible.
