### ISSUE TITLE
Links rendered to unusable menu on small window sizes

### ISSUE THREAD

**Issue by ctgraham** [ulsdevteam/ccvgd-frontend#24]
When the interface is rendered on narrow window sizes, the links 单村庄搜索 and
多村庄搜索 are collapsed to a menu, but the menu does not respond to click events to expand for visible options.

![image](https://user-images.githubusercontent.com/7001322/130693451-4db083e2-80b9-4405-9e1a-cbd2bc94bf64.png)

**Comment by Xiaoxin-He** [comment]
Hey Clinton, good catch! But those responsive design issues will be fixed after all multi-village search features are done and test pass

**Comment by ctgraham** [comment]
Not currently reproducible.
